[package]
name = "omni_lock_poc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-sdk = {version = "2.5", features = ["default"]}
ckb-types = "0.108"
anyhow = "1.0"
ckb-hash = "=0.108.0"